name: pub

on:
  push:
    tags: ['v*']

jobs:
  pub:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
    - run: cargo build --all-features
    - run: cargo test --all-features
    - run: cargo clippy --all-targets --all-features -- --deny warnings
    - run: cargo publish --token "$CARGO_REGISTRY_TOKEN"
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
